name: Backend Deploy to AWS S3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run tests
      working-directory: ./backend
      run: npm test --if-present

    - name: Run linting
      working-directory: ./backend
      run: npm run lint --if-present

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Build backend (if needed)
      working-directory: ./backend
      run: npm run build --if-present

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3 bucket
      run: |
        aws s3 sync ./backend s3://${{ secrets.AWS_S3_BUCKET_NAME }} \
          --exclude "node_modules/*" \
          --exclude ".git/*" \
          --exclude "test/*" \
          --delete
      working-directory: ./
